#
# more information can be found here http://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.role

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    options:
        html5_validate: false # does not use html5 validation

   
    templates:
        # default global templates
        # the layout template include javascript/stylesheet to the formatter bundle,
        # if you don't need it use the default one: SonataAdminBundle::standard_layout.html.twig
        layout:  SonataAdminBundle::layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default value if done set, actions templates, should extends a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: center, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> You can customize this dashboard by editing the sonata_admin.yml file. The current dashboard presents the recent items from the NewsBundle and a timeline with the latest action"} }
            - { position: right, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            - { position: right, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 7, mode: admin }}
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
services:
   stc.banner.admin.BannerType:
      class: STC\BannerBundle\Admin\BannerTypeAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manage Banner, label: Banner Type }
      arguments: [null, STC\BannerBundle\Entity\BannerType, STCBannerBundle:BannerTypeAdmin]

   stc.banner.admin.Banner:
      class: STC\BannerBundle\Admin\BannerAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Manage Banner, label: Banners }
      arguments: [null, STC\BannerBundle\Entity\Banner, STCBannerBundle:BannerAdmin]